usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /

tapas:
    resource: "@tapasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
