tapas_homepage:
    path:     /
    defaults: { _controller: tapasBundle:tapas:index }

tapas_crear:
    path:     /crearTapas
    defaults: { _controller: tapasBundle:tapas:crearTapa }

tapas_mostrar:
    path:     /mostrarTapas
    defaults: { _controller: tapasBundle:tapas:mostrarTapa }

tapas_mostrarId:
    path:     /mostrarTapasId/{id}
    defaults: { _controller: tapasBundle:tapas:mostrarTapaId }

tapas_borrar:
    path:     /borrarTapas/{id}
    defaults: { _controller: tapasBundle:tapas:borrarTapa }
